/**
 * Created by xiaozhu on 2017/8/6.
 */

export const GET_ARTICLELIST="GET_ARTICLELIST"
export const GET_ARTICLEDETAIL="GET_ARTICLEDETAIL"
export const GET_EDITARTICLE="GET_EDITARTICLE"
export const GET_ADMIN_ARTICLELIST="GET_ADMIN_ARTICLELIST"
export const CHECK_ARTICLECODE="CHECK_ARTICLECODE"

export const LOGIN="LOGIN"